version: "3"

services:
  db:
    image: mysql/mysql-server:5.7
    env_file: ./.env
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_DATABASE=${DB_NAME}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
    volumes:
      - todo-db:/var/lib/mysql
  app:
    depends_on:
      - db
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports :
      - "8080:8080"
volumes:
  todo-db:
